package com.sp.entity;
// Generated 12 mai 2022, 16:44:08 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import java.util.List;

/**
 * UserCard generated by hbm2java
 */
@Entity
@Table(name = "tag_card", schema = "public")
public class CardTag implements java.io.Serializable {
	@Id
	@GeneratedValue
	private int id;
	private int cardId;
	private String tag;

	public CardTag() {
	}

	public CardTag(int id) {
		this.id = id;
	}

	public CardTag(int CardId, String tag) {
		this.cardId = CardId;
		this.tag = tag;
	}


	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "cardId")
	public int getCardId() {
		return this.cardId;
	}

	public void setCardId(int cardId) {
		this.cardId = cardId;
	}

	@Column(name = "tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}
}
