/*package com.sp.entity;
// Generated 12 mai 2022, 16:44:08 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserCardId generated by hbm2java
 
@Embeddable
public class CardTagId implements java.io.Serializable {

	private int tagId;
	private int cardId;

	public CardTagId() {
	}

	public CardTagId(int tagId, int userId) {
		this.tagId = tagId;
		this.cardId = userId;
	}

	@Column(name = "card_id", nullable = false)
	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int cardId) {
		this.tagId = cardId;
	}

	@Column(name = "user_id", nullable = false)
	public int getCardId() {
		return this.cardId;
	}

	public void setCardId(int CardId) {
		this.cardId = CardId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CardTagId))
			return false;
		CardTagId castOther = (CardTagId) other;

		return (this.getTagId() == castOther.getTagId()) && (this.getCardId() == castOther.getCardId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCardId();
		result = 37 * result + this.getCardId();
		return result;
	}

}*/
