package com.sp.entity;
// Generated 12 mai 2022, 16:44:08 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "transaction", schema = "public")
public class Transaction implements java.io.Serializable {

	private int id;
	private Integer cardId;
	private Integer sellerId;
	private Date dateCreation;
	private Integer buyerId;
	private Date dateBuy;

	public Transaction() {
	}

	public Transaction(int id) {
		this.id = id;
	}

	public Transaction(int id, Integer cardId, Integer sellerId, Date dateCreation, Integer buyerId, Date dateBuy) {
		this.id = id;
		this.cardId = cardId;
		this.sellerId = sellerId;
		this.dateCreation = dateCreation;
		this.buyerId = buyerId;
		this.dateBuy = dateBuy;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "card_id")
	public Integer getCardId() {
		return this.cardId;
	}

	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	@Column(name = "seller_id")
	public Integer getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(Integer sellerId) {
		this.sellerId = sellerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_creation", length = 13)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "buyer_id")
	public Integer getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(Integer buyerId) {
		this.buyerId = buyerId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_buy", length = 13)
	public Date getDateBuy() {
		return this.dateBuy;
	}

	public void setDateBuy(Date dateBuy) {
		this.dateBuy = dateBuy;
	}

}
