package com.sp.entity;
// Generated 12 mai 2022, 16:44:08 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserCardId generated by hbm2java
 */
@Embeddable
public class UserCardId implements java.io.Serializable {

	private int cardId;
	private int userId;

	public UserCardId() {
	}

	public UserCardId(int cardId, int userId) {
		this.cardId = cardId;
		this.userId = userId;
	}

	@Column(name = "card_id", nullable = false)
	public int getCardId() {
		return this.cardId;
	}

	public void setCardId(int cardId) {
		this.cardId = cardId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserCardId))
			return false;
		UserCardId castOther = (UserCardId) other;

		return (this.getCardId() == castOther.getCardId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCardId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
