package com.sp.entity;
// Generated 12 mai 2022, 16:44:08 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserCard generated by hbm2java
 */
@Entity
@Table(name = "user_card", schema = "public")
public class UserCard implements java.io.Serializable {

	private UserCardId id;
	private Integer quantity;
	private Integer energy;

	public UserCard() {
	}

	public UserCard(UserCardId id) {
		this.id = id;
	}

	public UserCard(UserCardId id, Integer quantity, Integer energy) {
		this.id = id;
		this.quantity = quantity;
		this.energy = energy;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cardId", column = @Column(name = "card_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public UserCardId getId() {
		return this.id;
	}

	public void setId(UserCardId id) {
		this.id = id;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getEnergy() {
		return energy;
	}

	public void setEnergy(Integer energy) {
		this.energy = energy;
	}

}
